### ISSUE TITLE
Is it possible to build/export it as legacy

### ISSUE THREAD

**Issue by PH4NTOMiki** [Charca/sapper-blog-template#16]
I really like your template,  but I just think it would be better if it could be built/exported as legacy build, I tried running `npx sapper build --legacy` and `npx sapper export --legacy` but it doesn't work, and I think that you should update some versions in `package.json` most importantly `svelte` and `sapper` and also some other libraries/dependencies.

Thank you in advance
Mihael

**Comment by PH4NTOMiki** [comment]
@Charca @tommywalkie and once again thank you for your dedication

**Comment by Charca** [comment]
Hey @PH4NTOMiki, thanks for bringing this up. I've fixed it in #17, so if you pull the latest from the master branch, it should be working fine now. Try using: `npm run build -- --legacy`.
