### ISSUE TITLE
Question about structure

### ISSUE THREAD

**Issue by budparr** [Charca/sapper-blog-template#3]
Hi @Charca Thanks very much for creating this. I'm curious about the structure you've used. Did you create JSON for `[slug]` and `index` and then read them into the `svelte` file because that was necessary for Sapper server routes, or are those just a nice-to-have?

Thanks again!

**Comment by Charca** [comment]
Hey @budparr. That's the way Svelte routes work.

What you return from `blog/index.json.js` then is available when you fetch the `blog.json` endpoint from the client-side. Same with `blog/[slug].json.js`, only that the name of the endpoint is variable depending on the route.
