### ISSUE TITLE
'Deploy with Netlify' needs additional step to get deployments to work

### ISSUE THREAD

**Issue by irab** [Charca/sapper-blog-template#32]
Hi there, great template!

I just tried to deploy this to Netlify and it failed on the first deployment:

```
Deploy did not succeed: Deploy directory '__sapper__/export' does not exist
```

 Looks like I needed to update the build command from `npm run build` to `npm run build && npm run export`.

Once I did this it deployed fine.

**Comment by irab** [comment]
Looks like you might be to set the default **build command** in a netlify.toml config:
https://docs.netlify.com/configure-builds/file-based-configuration/

**Comment by Charca** [comment]
Thanks @irab! I've added a [netlify.toml](https://github.com/Charca/sapper-blog-template/blob/master/netlify.toml) file with the right command.
